name: music_app
description: The music app ui sample.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_icons: any
  audioplayers: ^0.20.1
  provider: ^6.0.2
  shared_preferences: ^2.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sound/
    - assets/images/
